#!/bin/bash

# Update & upgrade
sudo apt update &&
sudo apt upgrade -y

# Essentials
sudo apt install -y curl git tmux neovim

# Node.js
sudo apt install -y nodejs npm

# Nginx & PHP
sudo apt install -y nginx php8.4-cli php8.4-fpm

# Java & Gradle
sudo apt install -y openjdk-21-jdk
sudo snap install gradle --classic

# PostgreSQL
sudo apt install -y postgresql postgresql-contrib

# -----------------
# Minimal GUI
# -----------------
sudo apt install -y xorg firefox

# -----------------
# Containerization Tools
# -----------------
sudo apt install -y docker.io docker-compose podman
sudo apt install -y kubectl  # optional

# -----------------
# Networking and maintenance
# -----------------
sudo apt instal -y wget	
sudo apt install -y btop htop
sudo apt install -y openssh-server network-manager

# -----------------
# Check versions
# -----------------
echo
echo "INSTALL SUCCESSFUL"
echo "node: $(node -v)"
echo "npm: $(npm -v)"
echo "git: $(git --version)"
echo "curl: $(curl --version | head -n1)"
echo "Nginx: $(nginx -v 2>&1)"
echo "docker: $(docker --version)"
echo "docker-compose: $(docker-compose --version)"
echo "podman: $(podman --version)"
echo "kubectl: $(kubectl version --client --short)"
echo "firefox: $(firefox --version)"
